global using System.Net;
global using System.Net.Sockets;
global using GeoConvert;
global using GeoConvert.Web.Components;
global using GeoConvert.Web.Services;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.StaticFiles;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.Logging;
global using Microsoft.JSInterop;
global using Microsoft.Playwright;
global using TUnit.Core;
global using TUnit.Assertions;
global using TUnit.Assertions.Extensions;
global using static VerifyTUnit.Verifier;
